  const publicationsData = {
    "2025":[
        {title:"IoT Malware Network Traffic Detection using Deep Learning and GraphSAGE Models",
        authors: ["Nikesh Prajapati", "Bimal Karki", "Saroj Gopali", "Akbar Siami Namin"],
        link: "https://arxiv.org/abs/2507.10758"
        }
    ],
    "2024": [
      {
        title: "The performance of the LSTM-based code generated by Large Language Models (LLMs) in forecasting time series data",
        authors: ["Saroj Gopali", "Sima Siami-Namini", "Faranak Abri", "Akbar Siami Namin"],
        link: "https://www.sciencedirect.com/science/article/pii/S2949719124000682"
      },
      {
        title: "The Applicability of LLMs in Generating Textual Samples for Analysis of Imbalanced Datasets",
        authors: ["Saroj Gopali", "Faranak Abri", "Akbar Siami Namin", "Keith S Jones"],
        link: "https://ieeexplore.ieee.org/abstract/document/10683735/"
      },
      {
        title: "A Comparative Multivariate Analysis of VAR and Deep Learning-based Models for Forecasting Volatile Time Series Data",
        authors: ["Saroj Gopali", "Sima Siami-Namini", "Faranak Abri", "Akbar Siami Namin"],
        link: "https://ieeexplore.ieee.org/abstract/document/10640372/"
      }
    ],
    "2023": [
      {
        title: "A survey on blockchain-based federated learning and data privacy",
        authors: ["Bipin Chhetri", "Saroj Gopali", "Rukayat Olapojoye", "Samin Dehbashi", "Akbar Siami Namin"],
        link: "https://ieeexplore.ieee.org/abstract/document/10196842/"
      },
      {
        title: "The performance of sequential deep learning models in detecting phishing websites using contextual features of URLs",
        authors: ["Saroj Gopali", "Akbar S Namin", "Faranak Abri", "Keith S Jones"],
        link: "https://dl.acm.org/doi/abs/10.1145/3605098.3636164"
      }
    ],
    "2022": [
      {
        title: "Vulnerability detection in smart contracts using deep learning",
        authors: ["Saroj Gopali", "Zulfiqar Ali Khan", "Bipin Chhetri", "Bimal Karki", "Akbar Siami Namin"],
        link: "https://ieeexplore.ieee.org/abstract/document/9842527/"
      },
      {
        title: "A comparison of TCN and LSTM models in detecting anomalies in time series data",
        authors: ["Saroj Gopali", "Faranak Abri", "Sima Siami-Namini", "Akbar Siami Namin"],
        link: "https://ieeexplore.ieee.org/abstract/document/9671488/"
      },
      {
        title: "Deep learning-based time-series analysis for detecting anomalies in internet of things",
        authors: ["Saroj Gopali", "Akbar Siami Namin"],
        link: "https://www.mdpi.com/2079-9292/11/19/3205"
      }
    ],
    "2021": [
      {
        title: "HyPA: a hybrid password-based authentication mechanism",
        authors: ["Saroj Gopali", "Pranaya Sharma", "Praveen Kumar Khethavath", "Doyel Pal"],
        link: "https://link.springer.com/chapter/10.1007/978-3-030-73100-7_47"
      }
    ]
  };
  
  function renderPublications(data) {
    const container = document.getElementById("publication-list");

    const sortedYears = Object.keys(data).sort((a, b) => b - a); // Sort descending

    sortedYears.forEach((year) => {
      const yearSection = document.createElement("div");
      yearSection.className = "year-section";

      const yearHeader = document.createElement("h3");
      yearHeader.className = "year-header";
      yearHeader.textContent = year;
      yearSection.appendChild(yearHeader);

      const yearPubs = document.createElement("div");
      yearPubs.className = "year-publications";

      data[year].forEach((pub) => {
        const article = document.createElement("article");
        article.className = "publication";

        const title = document.createElement("h4");
        const link = document.createElement("a");
        link.href = pub.link;
        link.target = "_blank";
        link.textContent = pub.title;
        title.appendChild(link);

        const authors = document.createElement("p");
        authors.className = "authors";
        authors.innerHTML = pub.authors
          .map((author) =>
            author === "Saroj Gopali"
              ? `<strong>${author}</strong>`
              : author
          )
          .join(" and ");

        const options = document.createElement("div");
        options.className = "paper-options";

        const paperLink = document.createElement("a");
        paperLink.href = pub.link;
        paperLink.target = "_blank";
        paperLink.className = "paper-option";
        paperLink.innerHTML = `<i class="fas fa-file-pdf"></i> View Paper`;

        options.appendChild(paperLink);
        article.appendChild(title);
        article.appendChild(authors);
        article.appendChild(options);
        yearPubs.appendChild(article);
      });

      yearSection.appendChild(yearPubs);
      container.appendChild(yearSection);
    });
  }

  renderPublications(publicationsData);


  function renderLatestPublication(data) {
  const container = document.getElementById("latest-publication");

  // Get years and sort them descending
  const sortedYears = Object.keys(data).sort((a, b) => b - a);

  for (const year of sortedYears) {
    if (data[year] && data[year].length > 0) {
      const pub = data[year][0]; // first publication of the latest year

      const article = document.createElement("article");
      article.className = "publication";

      const title = document.createElement("h4");
      const link = document.createElement("a");
      link.href = pub.link;
      link.target = "_blank";
      link.textContent = pub.title;
      title.appendChild(link);

      const authors = document.createElement("p");
      authors.className = "authors";
      authors.innerHTML = pub.authors
        .map((author) =>
          author === "Saroj Gopali"
            ? `<strong>${author}</strong>`
            : author
        )
        .join(" and ");

      const options = document.createElement("div");
      options.className = "paper-options";

      const paperLink = document.createElement("a");
      paperLink.href = pub.link;
      paperLink.target = "_blank";
      paperLink.className = "paper-option";
      paperLink.innerHTML = `<i class="fas fa-file-pdf"></i> View Paper`;

      options.appendChild(paperLink);
      article.appendChild(title);
      article.appendChild(authors);
      article.appendChild(options);

      container.appendChild(article);
      break; // only show the top 1
    }
  }
}

// renderPublications(publicationsData);
renderLatestPublication(publicationsData);

