// ============================================
// Publications - Semantic Scholar API + Fallback
// ============================================

// Manual fallback data (all 11 papers)
var publicationsData = {
  "2025": [
    {
      "title": "In-Context and Few-Shots Learning for Forecasting Time Series Data Based on Large Language Models",
      "authors": [
        "Saroj Gopali",
        "Bipin Chhetri",
        "Deepika Giri",
        "Sima Siami‐Namini",
        "A. Namin"
      ],
      "venue": "BigData Congress [Services Society]",
      "link": "https://arxiv.org/abs/2512.07705",
      "doi": "10.1109/BigData66926.2025.11401073",
      "citationCount": 1
    },
    {
      "title": "IoT Malware Network Traffic Detection using Deep Learning and GraphSAGE Models",
      "authors": [
        "Nikesh Prajapati",
        "B. Karki",
        "Saroj Gopali",
        "A. Namin"
      ],
      "venue": "Annual International Computer Software and Applications Conference",
      "link": "https://arxiv.org/abs/2507.10758",
      "doi": "10.1109/COMPSAC65507.2025.00252",
      "citationCount": 0
    },
    {
      "title": "A data privacy and deep learning based AMR dashboard for rural and regional veterinary practices in Texas",
      "authors": [
        "Saroj Gopali",
        "Tianxi Ji",
        "Marcelo Schmidt",
        "N. Zimmerman",
        "B. Awosile"
      ],
      "venue": "Frontiers in Veterinary Science",
      "link": "https://doi.org/10.3389/fvets.2025.1646675",
      "doi": "10.3389/fvets.2025.1646675",
      "citationCount": 0
    }
  ],
  "2024": [
    {
      "title": "The Performance of the LSTM-based Code Generated by Large Language Models (LLMs) in Forecasting Time Series Data",
      "authors": [
        "Saroj Gopali",
        "Sima Siami‐Namini",
        "F. Abri",
        "A. Namin"
      ],
      "venue": "Natural Language Processing Journal",
      "link": "https://arxiv.org/abs/2411.18731",
      "doi": "10.1016/j.nlp.2024.100120",
      "citationCount": 10
    },
    {
      "title": "A Comparative Multivariate Analysis of VAR and Deep Learning-Based Models for Forecasting Volatile Time Series Data",
      "authors": [
        "Saroj Gopali",
        "Sima Siami‐Namini",
        "F. Abri",
        "Akbar Siami Namin"
      ],
      "venue": "IEEE Access",
      "link": "https://doi.org/10.1109/ACCESS.2024.3447354",
      "doi": "10.1109/ACCESS.2024.3447354",
      "citationCount": 9
    },
    {
      "title": "The Performance of Sequential Deep Learning Models in Detecting Phishing Websites Using Contextual Features of URLs",
      "authors": [
        "Saroj Gopali",
        "A. Namin",
        "F. Abri",
        "Keith S. Jones"
      ],
      "venue": "ACM Symposium on Applied Computing",
      "link": "https://arxiv.org/abs/2404.09802",
      "doi": "10.1145/3605098.3636164",
      "citationCount": 9
    },
    {
      "title": "The Applicability of LLMs in Generating Textual Samples for Analysis of Imbalanced Datasets",
      "authors": [
        "Saroj Gopali",
        "F. Abri",
        "Akbar Siami Namin",
        "Keith S. Jones"
      ],
      "venue": "IEEE Access",
      "link": "https://doi.org/10.1109/ACCESS.2024.3463400",
      "doi": "10.1109/ACCESS.2024.3463400",
      "citationCount": 6
    }
  ],
  "2023": [
    {
      "title": "A Survey on Blockchain-Based Federated Learning and Data Privacy",
      "authors": [
        "Bipin Chhetri",
        "Saroj Gopali",
        "Rukayat Olapojoye",
        "Samin Dehbashi",
        "A. Namin"
      ],
      "venue": "Annual International Computer Software and Applications Conference",
      "link": "https://arxiv.org/abs/2306.17338",
      "doi": "10.1109/COMPSAC57700.2023.00199",
      "citationCount": 24
    }
  ],
  "2022": [
    {
      "title": "Deep Learning-Based Time-Series Analysis for Detecting Anomalies in Internet of Things",
      "authors": [
        "Saroj Gopali",
        "Akbar Siami Namin"
      ],
      "venue": "Electronics",
      "link": "https://doi.org/10.3390/electronics11193205",
      "doi": "10.3390/electronics11193205",
      "citationCount": 20
    },
    {
      "title": "Vulnerability Detection in Smart Contracts Using Deep Learning",
      "authors": [
        "Saroj Gopali",
        "Z. Khan",
        "Bipin Chhetri",
        "B. Karki",
        "A. Namin"
      ],
      "venue": "Annual International Computer Software and Applications Conference",
      "link": "https://doi.org/10.1109/COMPSAC54236.2022.00197",
      "doi": "10.1109/COMPSAC54236.2022.00197",
      "citationCount": 9
    }
  ],
  "2021": [
    {
      "title": "A Comparison of TCN and LSTM Models in Detecting Anomalies in Time Series Data",
      "authors": [
        "Saroj Gopali",
        "F. Abri",
        "Sima Siami‐Namini",
        "A. Namin"
      ],
      "venue": "2021 IEEE International Conference on Big Data (Big Data)",
      "link": "https://doi.org/10.1109/BigData52589.2021.9671488",
      "doi": "10.1109/BigData52589.2021.9671488",
      "citationCount": 71
    },
    {
      "title": "A Comparative Study of Detecting Anomalies in Time Series Data Using LSTM and TCN Models",
      "authors": [
        "Saroj Gopali",
        "F. Abri",
        "Sima Siami‐Namini",
        "A. Namin"
      ],
      "venue": "arXiv.org",
      "link": "https://arxiv.org/abs/2112.09293",
      "doi": "",
      "citationCount": 16
    },
    {
      "title": "HyPA: A Hybrid Password-Based Authentication Mechanism",
      "authors": [
        "Saroj Gopali",
        "P. Sharma",
        "Praveen Khethavath",
        "Doyel Pal"
      ],
      "venue": "",
      "link": "https://doi.org/10.1007/978-3-030-73100-7_47",
      "doi": "10.1007/978-3-030-73100-7_47",
      "citationCount": 1
    }
  ]
};

// Semantic Scholar API fetch
var SEMANTIC_SCHOLAR_API = 'https://api.semanticscholar.org/graph/v1/author/2101065912/papers?fields=title,year,authors,url,citationCount,venue,externalIds&limit=50';

function getManualLink(title) {
  if (!title) return '';
  var allYears = Object.keys(publicationsData);
  for (var i = 0; i < allYears.length; i++) {
    var pubs = publicationsData[allYears[i]];
    for (var j = 0; j < pubs.length; j++) {
      if (pubs[j].title && title.toLowerCase().indexOf(pubs[j].title.substring(0, 30).toLowerCase()) !== -1) {
        return pubs[j].link || '';
      }
    }
  }
  return '';
}

function fetchFromSemanticScholar() {
  return fetch(SEMANTIC_SCHOLAR_API)
    .then(function (response) {
      if (!response.ok) throw new Error('API request failed');
      return response.json();
    })
    .then(function (data) {
      if (!data.data || data.data.length === 0) throw new Error('No data returned');
      return transformApiData(data.data);
    });
}

// Clean venue name map — override messy API venue names
var VENUE_OVERRIDES = {
  'IoT Malware Network Traffic Detection': 'IEEE COMPSAC 2025',
  'In-Context and Few-Shots Learning': 'arXiv Preprint',
  'data privacy and deep learning based AMR': 'Frontiers in Veterinary Science',
  'LSTM-based Code Generated by Large Language': 'Machine Learning with Applications',
  'Applicability of LLMs in Generating Textual': 'IEEE Access',
  'Comparative Multivariate Analysis of VAR': 'IEEE Access',
  'Sequential Deep Learning Models in Detecting Phishing': 'ACM SAC 2024',
  'Blockchain-Based Federated Learning': 'IEEE COMPSAC 2023',
  'Vulnerability Detection in Smart Contracts': 'IEEE COMPSAC 2022',
  'Comparison of TCN and LSTM Models': 'IEEE BigData 2021',
  'Deep Learning-Based Time-Series Analysis': 'MDPI Electronics',
  'Comparative Study of Detecting Anomalies': 'MDPI Electronics',
  'HyPA': 'Springer FICC 2021'
};

function getCleanVenue(title, apiVenue) {
  for (var key in VENUE_OVERRIDES) {
    if (title && title.indexOf(key) !== -1) {
      return VENUE_OVERRIDES[key];
    }
  }
  // Also try manual fallback data for matching titles
  var allYears = Object.keys(publicationsData);
  for (var i = 0; i < allYears.length; i++) {
    var pubs = publicationsData[allYears[i]];
    for (var j = 0; j < pubs.length; j++) {
      if (title && pubs[j].title && title.toLowerCase().indexOf(pubs[j].title.substring(0, 30).toLowerCase()) !== -1) {
        return pubs[j].venue;
      }
    }
  }
  return apiVenue || '';
}

function transformApiData(papers) {
  var grouped = {};

  papers.forEach(function (paper) {
    var year = paper.year ? String(paper.year) : 'Unknown';
    if (!grouped[year]) grouped[year] = [];

    var authors = [];
    if (paper.authors) {
      authors = paper.authors.map(function (a) { return a.name; });
    }

    var doi = null;
    var ext = paper.externalIds || {};
    if (ext.DOI) doi = ext.DOI;

    // Link priority: arXiv > DOI > manual fallback > Semantic Scholar
    var link = '';
    if (ext.ArXiv) {
      link = 'https://arxiv.org/abs/' + ext.ArXiv;
    } else if (doi) {
      link = 'https://doi.org/' + doi;
    } else {
      // Check manual data for a better link
      var manualLink = getManualLink(paper.title);
      link = manualLink || paper.url || '';
    }

    // Use clean venue name
    var venue = getCleanVenue(paper.title, paper.venue);

    grouped[year].push({
      title: paper.title || 'Untitled',
      authors: authors,
      venue: venue,
      link: link,
      doi: doi,
      citationCount: paper.citationCount || 0
    });
  });

  // Sort papers within each year by citation count descending
  Object.keys(grouped).forEach(function (year) {
    grouped[year].sort(function (a, b) { return b.citationCount - a.citationCount; });
  });

  return grouped;
}

function renderPublications(data, source) {
  var container = document.getElementById('publications-auto');
  if (!container) {
    container = document.getElementById('publication-list');
  }
  if (!container) return;

  container.innerHTML = '';

  var sortedYears = Object.keys(data).sort(function (a, b) { return parseInt(b) - parseInt(a); });

  sortedYears.forEach(function (year) {
    if (year === 'Unknown') return;

    var yearSection = document.createElement('div');
    yearSection.className = 'year-section fade-in';

    var yearHeader = document.createElement('h3');
    yearHeader.className = 'year-header';
    yearHeader.textContent = year;
    yearSection.appendChild(yearHeader);

    var yearPubs = document.createElement('div');
    yearPubs.className = 'year-publications';

    data[year].forEach(function (pub) {
      var article = document.createElement('article');
      article.className = 'publication';

      // Title
      var title = document.createElement('h4');
      if (pub.link) {
        var link = document.createElement('a');
        link.href = pub.link;
        link.target = '_blank';
        link.rel = 'noopener noreferrer';
        link.textContent = pub.title;
        title.appendChild(link);
      } else {
        title.textContent = pub.title;
      }

      // Authors
      var authors = document.createElement('p');
      authors.className = 'authors';
      authors.innerHTML = pub.authors
        .map(function (author) {
          if (author === 'Saroj Gopali' || author === 'S. Gopali') {
            return '<strong>' + author + '</strong>';
          }
          return author;
        })
        .join(', ');

      // Venue
      var venue = document.createElement('p');
      venue.className = 'venue';
      venue.textContent = pub.venue || '';

      // Meta (citation badge + links)
      var meta = document.createElement('div');
      meta.className = 'pub-meta';

      // Citation count removed per user request

      var options = document.createElement('div');
      options.className = 'paper-options';

      if (pub.link) {
        var paperLink = document.createElement('a');
        paperLink.href = pub.link;
        paperLink.target = '_blank';
        paperLink.rel = 'noopener noreferrer';
        paperLink.className = 'paper-option';
        paperLink.innerHTML = '<i class="fas fa-external-link-alt"></i> Paper';
        options.appendChild(paperLink);
      }

      if (pub.doi) {
        var doiLink = document.createElement('a');
        doiLink.href = 'https://doi.org/' + pub.doi;
        doiLink.target = '_blank';
        doiLink.rel = 'noopener noreferrer';
        doiLink.className = 'paper-option';
        doiLink.innerHTML = '<i class="ai ai-doi"></i> DOI';
        options.appendChild(doiLink);
      }

      meta.appendChild(options);

      article.appendChild(title);
      article.appendChild(authors);
      if (pub.venue) article.appendChild(venue);
      article.appendChild(meta);
      yearPubs.appendChild(article);
    });

    yearSection.appendChild(yearPubs);
    container.appendChild(yearSection);
  });

  // Update note
  var noteEl = document.getElementById('pub-update-note');
  if (noteEl) {
    if (source === 'api') {
      noteEl.textContent = 'Auto-fetched from Semantic Scholar on ' + new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    } else {
      noteEl.textContent = '';
    }
  }

  // Trigger scroll animations
  setTimeout(function () {
    document.querySelectorAll('.fade-in').forEach(function (el) {
      el.classList.add('visible');
    });
  }, 200);
}

// Google Scholar fetch via SerpAPI proxy (free tier: 100 searches/month)
// Alternative: use scholarly-api or google-scholar-scraper proxy
var GOOGLE_SCHOLAR_PROXY = 'https://serpapi.com/search.json?engine=google_scholar_author&author_id=Zt79RTIAAAAJ&num=40';

function fetchFromGoogleScholar() {
  // Use a CORS proxy to access Google Scholar data
  // Option 1: SerpAPI (if API key is set)
  // Option 2: scholar.google.com via allorigins proxy
  var proxyUrl = 'https://api.allorigins.win/raw?url=' + encodeURIComponent(
    'https://scholar.google.com/citations?user=Zt79RTIAAAAJ&hl=en&cstart=0&pagesize=40&sortby=pubdate&view_op=list_works'
  );

  return fetch(proxyUrl)
    .then(function (response) {
      if (!response.ok) throw new Error('Google Scholar proxy failed');
      return response.text();
    })
    .then(function (html) {
      return parseGoogleScholarHTML(html);
    });
}

function parseGoogleScholarHTML(html) {
  var grouped = {};

  // Extract using regex (more reliable than DOMParser for proxied HTML)
  var titleRegex = /<a[^>]*class="gsc_a_at"[^>]*href="([^"]*)"[^>]*>([^<]+)<\/a>/g;
  var grayRegex = /<div class="gs_gray">([^<]+)<\/div>/g;
  var yearRegex = /<span class="gsc_a_h gsc_a_hc gs_ibl">(\d{4})<\/span>/g;

  var titles = [], links = [], grays = [], years = [];
  var m;

  while ((m = titleRegex.exec(html)) !== null) {
    links.push(m[1]);
    titles.push(m[2].trim());
  }
  while ((m = grayRegex.exec(html)) !== null) {
    grays.push(m[1].trim());
  }
  while ((m = yearRegex.exec(html)) !== null) {
    years.push(m[1]);
  }

  if (titles.length === 0) throw new Error('No papers parsed from Google Scholar');

  // grays alternate: authors, venue, authors, venue...
  for (var i = 0; i < titles.length; i++) {
    var title = titles[i];
    var link = links[i] || '';
    if (link && !link.startsWith('http')) {
      link = 'https://scholar.google.com' + link;
    }

    var authorsText = grays[i * 2] || '';
    var venue = grays[i * 2 + 1] || '';
    var year = years[i] || 'Unknown';
    var authors = authorsText.split(',').map(function (a) { return a.trim(); });

    if (!grouped[year]) grouped[year] = [];
    grouped[year].push({
      title: title,
      authors: authors,
      venue: venue,
      link: link,
      doi: null,
      citationCount: 0
    });
  }

  return grouped;
}

// Initialize publications with fallback chain:
// 1. Google Scholar via proxy (most accurate venue names)
// 2. Semantic Scholar API (best structured data)
// 3. Manual fallback data (always works)
(function () {
  console.log('[Pubs] Trying Google Scholar...');
  fetchFromGoogleScholar()
    .then(function (gsData) {
      console.log('[Pubs] Google Scholar succeeded');
      renderPublications(gsData, 'google-scholar');
    })
    .catch(function (err) {
      console.log('[Pubs] Google Scholar failed:', err.message, '— trying Semantic Scholar...');
      fetchFromSemanticScholar()
        .then(function (apiData) {
          console.log('[Pubs] Semantic Scholar succeeded');
          renderPublications(apiData, 'api');
        })
        .catch(function (err2) {
          console.log('[Pubs] Semantic Scholar failed:', err2.message, '— using fallback');
          renderPublications(publicationsData, 'fallback');
        });
    });
})();
