// ============================================
// Publications - Semantic Scholar API + Fallback
// ============================================

// Manual fallback data (all 11 papers)
var publicationsData = {
  "2025": [
    {
      title: "IoT Malware Network Traffic Detection using Deep Learning and GraphSAGE Models",
      authors: ["Nikesh Prajapati", "Bimal Karki", "Saroj Gopali", "Akbar Siami Namin"],
      venue: "IEEE COMPSAC 2025",
      link: "https://arxiv.org/abs/2507.10758",
      doi: null,
      citationCount: 0
    },
    {
      title: "In-Context and Few-Shots Learning for Forecasting Time Series Data based on Large Language Models",
      authors: ["Saroj Gopali", "Bipin Chhetri", "Deepika Giri", "Sima Siami-Namini", "Akbar Siami Namin"],
      venue: "arXiv Preprint",
      link: "https://arxiv.org/abs/2512.07705",
      doi: null,
      citationCount: 0
    },
    {
      title: "A Data Privacy and Deep Learning Based AMR Dashboard for Rural and Regional Veterinary Practices in Texas",
      authors: ["Saroj Gopali", "Tianxi Ji", "Marcelo Schmidt", "Nancy Zimmerman", "Babafela Awosile"],
      venue: "Frontiers in Veterinary Science",
      link: "https://www.frontiersin.org/journals/veterinary-science/articles/10.3389/fvets.2025.1646675/full",
      doi: "10.3389/fvets.2025.1646675",
      citationCount: 0
    }
  ],
  "2024": [
    {
      title: "The Performance of the LSTM-based Code Generated by Large Language Models (LLMs) in Forecasting Time Series Data",
      authors: ["Saroj Gopali", "Sima Siami-Namini", "Faranak Abri", "Akbar Siami Namin"],
      venue: "ScienceDirect - Machine Learning with Applications",
      link: "https://www.sciencedirect.com/science/article/pii/S2949719124000682",
      doi: "10.1016/j.mlwa.2024.100568",
      citationCount: 0
    },
    {
      title: "The Applicability of LLMs in Generating Textual Samples for Analysis of Imbalanced Datasets",
      authors: ["Saroj Gopali", "Faranak Abri", "Akbar Siami Namin", "Keith S Jones"],
      venue: "IEEE Access",
      link: "https://ieeexplore.ieee.org/abstract/document/10683735/",
      doi: "10.1109/ACCESS.2024.3462190",
      citationCount: 0
    },
    {
      title: "A Comparative Multivariate Analysis of VAR and Deep Learning-based Models for Forecasting Volatile Time Series Data",
      authors: ["Saroj Gopali", "Sima Siami-Namini", "Faranak Abri", "Akbar Siami Namin"],
      venue: "IEEE Access",
      link: "https://ieeexplore.ieee.org/abstract/document/10640372/",
      doi: "10.1109/ACCESS.2024.3443329",
      citationCount: 0
    },
    {
      title: "The Performance of Sequential Deep Learning Models in Detecting Phishing Websites Using Contextual Features of URLs",
      authors: ["Saroj Gopali", "Akbar S Namin", "Faranak Abri", "Keith S Jones"],
      venue: "ACM SAC 2024",
      link: "https://arxiv.org/abs/2404.09802",
      doi: null,
      citationCount: 0
    }
  ],
  "2023": [
    {
      title: "A Survey on Blockchain-based Federated Learning and Data Privacy",
      authors: ["Bipin Chhetri", "Saroj Gopali", "Rukayat Olapojoye", "Samin Dehbashi", "Akbar Siami Namin"],
      venue: "IEEE COMPSAC 2023",
      link: "https://ieeexplore.ieee.org/abstract/document/10196842/",
      doi: "10.1109/COMPSAC57700.2023.00178",
      citationCount: 0
    }
  ],
  "2022": [
    {
      title: "Vulnerability Detection in Smart Contracts Using Deep Learning",
      authors: ["Saroj Gopali", "Zulfiqar Ali Khan", "Bipin Chhetri", "Bimal Karki", "Akbar Siami Namin"],
      venue: "IEEE COMPSAC 2022",
      link: "https://ieeexplore.ieee.org/abstract/document/9842527/",
      doi: "10.1109/COMPSAC54236.2022.00099",
      citationCount: 0
    },
    {
      title: "A Comparison of TCN and LSTM Models in Detecting Anomalies in Time Series Data",
      authors: ["Saroj Gopali", "Faranak Abri", "Sima Siami-Namini", "Akbar Siami Namin"],
      venue: "IEEE BigData 2021",
      link: "https://ieeexplore.ieee.org/abstract/document/9671488/",
      doi: "10.1109/BigData52589.2021.9671488",
      citationCount: 0
    },
    {
      title: "Deep Learning-based Time-series Analysis for Detecting Anomalies in Internet of Things",
      authors: ["Saroj Gopali", "Akbar Siami Namin"],
      venue: "MDPI Electronics",
      link: "https://www.mdpi.com/2079-9292/11/19/3205",
      doi: "10.3390/electronics11193205",
      citationCount: 0
    }
  ],
  "2021": [
    {
      title: "HyPA: A Hybrid Password-based Authentication Mechanism",
      authors: ["Saroj Gopali", "Pranaya Sharma", "Praveen Kumar Khethavath", "Doyel Pal"],
      venue: "Springer - Advances in Information and Communication",
      link: "https://link.springer.com/chapter/10.1007/978-3-030-73100-7_47",
      doi: "10.1007/978-3-030-73100-7_47",
      citationCount: 0
    }
  ]
};

// Semantic Scholar API fetch
var SEMANTIC_SCHOLAR_API = 'https://api.semanticscholar.org/graph/v1/author/2101065912/papers?fields=title,year,authors,url,citationCount,venue,externalIds&limit=50';

function fetchFromSemanticScholar() {
  return fetch(SEMANTIC_SCHOLAR_API)
    .then(function (response) {
      if (!response.ok) throw new Error('API request failed');
      return response.json();
    })
    .then(function (data) {
      if (!data.data || data.data.length === 0) throw new Error('No data returned');
      return transformApiData(data.data);
    });
}

function transformApiData(papers) {
  var grouped = {};

  papers.forEach(function (paper) {
    var year = paper.year ? String(paper.year) : 'Unknown';
    if (!grouped[year]) grouped[year] = [];

    var authors = [];
    if (paper.authors) {
      authors = paper.authors.map(function (a) { return a.name; });
    }

    var doi = null;
    if (paper.externalIds && paper.externalIds.DOI) {
      doi = paper.externalIds.DOI;
    }

    var link = paper.url || '';
    if (paper.externalIds && paper.externalIds.ArXiv) {
      link = link || ('https://arxiv.org/abs/' + paper.externalIds.ArXiv);
    }

    grouped[year].push({
      title: paper.title || 'Untitled',
      authors: authors,
      venue: paper.venue || '',
      link: link,
      doi: doi,
      citationCount: paper.citationCount || 0
    });
  });

  // Sort papers within each year by citation count descending
  Object.keys(grouped).forEach(function (year) {
    grouped[year].sort(function (a, b) { return b.citationCount - a.citationCount; });
  });

  return grouped;
}

function renderPublications(data, source) {
  var container = document.getElementById('publications-auto');
  if (!container) {
    container = document.getElementById('publication-list');
  }
  if (!container) return;

  container.innerHTML = '';

  var sortedYears = Object.keys(data).sort(function (a, b) { return parseInt(b) - parseInt(a); });

  sortedYears.forEach(function (year) {
    if (year === 'Unknown') return;

    var yearSection = document.createElement('div');
    yearSection.className = 'year-section fade-in';

    var yearHeader = document.createElement('h3');
    yearHeader.className = 'year-header';
    yearHeader.textContent = year;
    yearSection.appendChild(yearHeader);

    var yearPubs = document.createElement('div');
    yearPubs.className = 'year-publications';

    data[year].forEach(function (pub) {
      var article = document.createElement('article');
      article.className = 'publication';

      // Title
      var title = document.createElement('h4');
      if (pub.link) {
        var link = document.createElement('a');
        link.href = pub.link;
        link.target = '_blank';
        link.rel = 'noopener noreferrer';
        link.textContent = pub.title;
        title.appendChild(link);
      } else {
        title.textContent = pub.title;
      }

      // Authors
      var authors = document.createElement('p');
      authors.className = 'authors';
      authors.innerHTML = pub.authors
        .map(function (author) {
          if (author === 'Saroj Gopali' || author === 'S. Gopali') {
            return '<strong>' + author + '</strong>';
          }
          return author;
        })
        .join(', ');

      // Venue
      var venue = document.createElement('p');
      venue.className = 'venue';
      venue.textContent = pub.venue || '';

      // Meta (citation badge + links)
      var meta = document.createElement('div');
      meta.className = 'pub-meta';

      // Citation count removed per user request

      var options = document.createElement('div');
      options.className = 'paper-options';

      if (pub.link) {
        var paperLink = document.createElement('a');
        paperLink.href = pub.link;
        paperLink.target = '_blank';
        paperLink.rel = 'noopener noreferrer';
        paperLink.className = 'paper-option';
        paperLink.innerHTML = '<i class="fas fa-external-link-alt"></i> Paper';
        options.appendChild(paperLink);
      }

      if (pub.doi) {
        var doiLink = document.createElement('a');
        doiLink.href = 'https://doi.org/' + pub.doi;
        doiLink.target = '_blank';
        doiLink.rel = 'noopener noreferrer';
        doiLink.className = 'paper-option';
        doiLink.innerHTML = '<i class="ai ai-doi"></i> DOI';
        options.appendChild(doiLink);
      }

      meta.appendChild(options);

      article.appendChild(title);
      article.appendChild(authors);
      if (pub.venue) article.appendChild(venue);
      article.appendChild(meta);
      yearPubs.appendChild(article);
    });

    yearSection.appendChild(yearPubs);
    container.appendChild(yearSection);
  });

  // Update note
  var noteEl = document.getElementById('pub-update-note');
  if (noteEl) {
    if (source === 'api') {
      noteEl.textContent = 'Auto-fetched from Semantic Scholar on ' + new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    } else {
      noteEl.textContent = '';
    }
  }

  // Trigger scroll animations
  setTimeout(function () {
    document.querySelectorAll('.fade-in').forEach(function (el) {
      el.classList.add('visible');
    });
  }, 200);
}

// Google Scholar fetch via SerpAPI proxy (free tier: 100 searches/month)
// Alternative: use scholarly-api or google-scholar-scraper proxy
var GOOGLE_SCHOLAR_PROXY = 'https://serpapi.com/search.json?engine=google_scholar_author&author_id=Zt79RTIAAAAJ&num=40';

function fetchFromGoogleScholar() {
  // Use a CORS proxy to access Google Scholar data
  // Option 1: SerpAPI (if API key is set)
  // Option 2: scholar.google.com via allorigins proxy
  var proxyUrl = 'https://api.allorigins.win/raw?url=' + encodeURIComponent(
    'https://scholar.google.com/citations?user=Zt79RTIAAAAJ&hl=en&cstart=0&pagesize=40&sortby=pubdate&view_op=list_works'
  );

  return fetch(proxyUrl)
    .then(function (response) {
      if (!response.ok) throw new Error('Google Scholar proxy failed');
      return response.text();
    })
    .then(function (html) {
      return parseGoogleScholarHTML(html);
    });
}

function parseGoogleScholarHTML(html) {
  var grouped = {};
  var parser = new DOMParser();
  var doc = parser.parseFromString(html, 'text/html');
  var rows = doc.querySelectorAll('.gsc_a_tr');

  rows.forEach(function (row) {
    var titleEl = row.querySelector('.gsc_a_at');
    var authorsEl = row.querySelector('.gs_gray');
    var yearEl = row.querySelector('.gsc_a_y span');

    if (!titleEl) return;

    var title = titleEl.textContent.trim();
    var link = titleEl.getAttribute('href') || '';
    if (link && !link.startsWith('http')) {
      link = 'https://scholar.google.com' + link;
    }

    var authorsText = authorsEl ? authorsEl.textContent.trim() : '';
    var authors = authorsText.split(',').map(function (a) { return a.trim(); });

    // Get venue (second .gs_gray element)
    var grays = row.querySelectorAll('.gs_gray');
    var venue = grays.length > 1 ? grays[1].textContent.trim() : '';

    var year = yearEl ? yearEl.textContent.trim() : 'Unknown';
    if (!year || year === '') year = 'Unknown';

    if (!grouped[year]) grouped[year] = [];
    grouped[year].push({
      title: title,
      authors: authors,
      venue: venue,
      link: link,
      doi: null,
      citationCount: 0
    });
  });

  if (Object.keys(grouped).length === 0) {
    throw new Error('No papers parsed from Google Scholar');
  }

  return grouped;
}

// Initialize publications with fallback chain:
// 1. Semantic Scholar API (best structured data)
// 2. Google Scholar via proxy (backup)
// 3. Manual fallback data (always works)
(function () {
  console.log('[Pubs] Trying Semantic Scholar...');
  fetchFromSemanticScholar()
    .then(function (apiData) {
      console.log('[Pubs] Semantic Scholar succeeded');
      renderPublications(apiData, 'api');
    })
    .catch(function (err) {
      console.log('[Pubs] Semantic Scholar failed:', err.message, '— trying Google Scholar...');
      fetchFromGoogleScholar()
        .then(function (gsData) {
          console.log('[Pubs] Google Scholar succeeded');
          renderPublications(gsData, 'google-scholar');
        })
        .catch(function (err2) {
          console.log('[Pubs] Google Scholar failed:', err2.message, '— using fallback');
          renderPublications(publicationsData, 'fallback');
        });
    });
})();
